# Generated by Django 3.0.5 on 2020-07-24 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20200724_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='name',
        ),
        migrations.AlterField(
            model_name='blogtable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
