# Generated by Django 3.0.5 on 2020-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0007_userdetail_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
