# Generated by Django 3.0.5 on 2020-07-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0008_userdetail_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetail',
            new_name='User',
        ),
    ]
