# Generated by Django 3.0.5 on 2020-07-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0012_auto_20200724_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtable',
            old_name='author',
            new_name='author_id',
        ),
    ]
