# Generated by Django 3.0.5 on 2020-07-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0013_auto_20200724_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtable',
            old_name='author_id',
            new_name='author',
        ),
    ]
