# Generated by Django 3.0.5 on 2020-07-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0014_auto_20200724_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
